import numpy as np
marks=np.array([[60,70,80],[70,80,90]])
print(marks)
print(np.mean(marks))
print("shape:",marks.shape)
result=np.mean(marks,axis=0)
result=np.median(marks,axis=0)
result=np.var(marks,axis=0)
result=np.std(marks,axis=0)
print(result)
print(result.shape)
result=np.mean(marks,axis=1)
result=np.median(marks,axis=1)
result=np.var(marks,axis=1)
result=np.std(marks,axis=1)
print(result)
print(result.shape)